df:
  boot:
    datasource:
      datasources:
        dream-flower:
          nodes:
            master:
              url: jdbc:mysql://localhost:3306/dream_flower?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false