server:
  port: 8088
spring:
  application:
    name: df-admin-service
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dream_flower?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: dream_flower
    password: dream_flower
mybatis:
  mapper-locations:
    - classpath:net/df/module/admin/xmlmapper/*.xml
  type-aliases-package: net.df.module.**.model
logging:
  level:
    net.df.module.admin.mapper: debug
df:
  boot:
    web:
      open-cors: true