server:
  port: 8088
spring:
  application:
    name: df-admin-service
  profiles:
    active: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/dream_flower?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: dream_flower
    password: dream_flower
  session:
    store-type: jdbc
    redis:
      flush-mode: on_save
      namespace: spring:session
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
    timeout: 1800s
mybatis:
  mapper-locations:
    - classpath:net/df/module/admin/xmlmapper/*.xml
  type-aliases-package: com.df4j.module.**.model
logging:
  level:
    com.df4j.module.admin.mapper: debug
df:
  boot:
    web:
      open-cors: true
      open-http-debug-log: true